title: â™¡ ğ–’ğ–Šğ–‰ğ–šğ–˜ğ–†ğ–ğ–—ğ–† â™¡
description: "Hacker offsec, escritora de filosofÃ­a y crÃ­tica cultural. Weltschmerz - libro de poesÃ­a gratuito. Goad Letters newsletter."
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark"
  back_home_text: "< inicio"
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

url: "https://medusahra.github.io"
lang: es

# Autor
author:
  name: Giovanna Gigi Chadid
  email: blackobjkt@protonmail.com

# SEO
tagline: "Hacker, offsec, filosofÃ­a, crÃ­tica cultural, poesÃ­a"

social:
  name: Gigi Chadid
  links:
    - https://github.com/medusahra
    - https://instagram.com/medusahra
    - https://x.com/medusahra

# CSS personalizado
sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      custom_css: /assets/css/style.css
