title: â™¡ ğ–’ğ–Šğ–‰ğ–šğ–˜ğ–†ğ–ğ–—ğ–† â™¡
description: 
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark"
  back_home_text: "< inicio"
  date_format: "%Y-% %d"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

url: "https://medusahra.github.io"

# Redes sociales (opcional)
author:
  name: Tu Nombre
  email: tuemail@ejemplo.com

# CSS personalizado
sass:
  style: compressed

# Incluir CSS custom
defaults:
  - scope:
      path: ""
    values:
      custom_css: /assets/css/style.css
